package com.admaroc.tecdoc.tecdocdata.repository;

import com.admaroc.tecdoc.tecdocdata.model.AllocationOfPartsListCoordinatesToContextSensitiveGraphics;
import com.admaroc.tecdoc.tecdocdata.model.compositeKeys.AllocationOfPartsListCoordinatesToContextSensitiveGraphicsId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AllocationOfPartsListCoordinatesToContextSensitiveGraphicsRepository extends JpaRepository<AllocationOfPartsListCoordinatesToContextSensitiveGraphics, AllocationOfPartsListCoordinatesToContextSensitiveGraphicsId> {


}
