package com.admaroc.tecdoc.tecdocdata.repository;

import com.admaroc.tecdoc.tecdocdata.model.AllocationOfCriteriaValuesToGAMandatoryCriteria;
import com.admaroc.tecdoc.tecdocdata.model.compositeKeys.AllocationOfCriteriaValuesToGAMandatoryCriteriaId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AllocationOfCriteriaValuesToGAMandatoryCriteriaRepository extends JpaRepository<AllocationOfCriteriaValuesToGAMandatoryCriteria, AllocationOfCriteriaValuesToGAMandatoryCriteriaId> {


}
