package com.admaroc.tecdoc.tecdocdata.repository;

import com.admaroc.tecdoc.tecdocdata.model.CountryRestrictionsForTheAllocationOfCVToIDNumbers;
import com.admaroc.tecdoc.tecdocdata.model.compositeKeys.CountryRestrictionsForTheAllocationOfCVToIDNumbersId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface CountryRestrictionsForTheAllocationOfCVToIDNumbersRepository extends JpaRepository<CountryRestrictionsForTheAllocationOfCVToIDNumbers, CountryRestrictionsForTheAllocationOfCVToIDNumbersId> {


}
