package com.admaroc.tecdoc.tecdocdata.repository;

import com.admaroc.tecdoc.tecdocdata.model.TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductArea;
import com.admaroc.tecdoc.tecdocdata.model.compositeKeys.TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaRepository extends JpaRepository<TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductArea, TheAllocationOfQuickStartIconsToNodesLeavesWithinOneProductAreaId> {


}
